service: appointment-app

frameworkVersion: "4.15.1"

provider:
  name: aws
  runtime: nodejs20.x

functions:
  hello:
    handler: src/functions/hello.handler
    events:
      - http:
          path: hello
          method: get
  get-schedule:
    handler: src/functions/get-schedule.handler
    events:
      - http:
          path: get-schedule
          method: get

plugins:
  - serverless-offline

custom:
  esbuild:
    bundle: true
    minify: false
    sourcemap: true
    exclude: ["aws-sdk"]
